language: ruby

rvm:
  - 2.6.3

cache: bundler

before_install:
  - gem update --system
  - gem install rubocop -v 0.70
  - gem install rspec -v 3.8.0
  - gem install bundler -v 2.0.1

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - rspec
  - rubocop
